Test/Controllers/DetailController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models;

namespace Test.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail ln
        public ActionResult lnDetails(int? id)
        {
            if (id == 0)
                return HttpNotFound();
            if (!id.HasValue)
                 return HttpNotFound();
            else
            {
                //converti json en string puis en object rootobject
                string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"\Data\Data.json");
                var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
                // search ln avec id 
                DataModel.LightNovel result = root.listLightNovels.Where(ln => ln.ID == id)
                                               .Select(ln => new DataModel.LightNovel
                                               {
                                                   ID = ln.ID,
                                                   Name = ln.Name,
                                                   Associated_Name = ln.Associated_Name,
                                                   Description = ln.Description,
                                                   Genre = ln.Genre,
                                                   Authors = ln.Authors,
                                                   Artits = ln.Artits,
                                                   Year = ln.Year,
                                                   Volume = ln.Volume,
                                                   Url = ln.Url,
                                                   Image = ln.Image
                                               }).FirstOrDefault();
                return View(result);
            }
        }

        // GET: Detail wn
        public ActionResult wnDetails(int? id)
        {
            if (id == 0)
                return HttpNotFound();
            if (!id.HasValue)
                return HttpNotFound();
            else
            {
                string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"\Data\Data.json");
                var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
                DataModel.WebNovel result = root.listWebNovels.Where(wn => wn.ID == id)
                                               .Select(wn => new DataModel.WebNovel
                                               {
                                                   ID = wn.ID,
                                                   Name = wn.Name,
                                                   Associated_Name = wn.Associated_Name,
                                                   Description = wn.Description,
                                                   Genre = wn.Genre,
                                                   Authors = wn.Authors,
                                                   Artits = wn.Artits,
                                                   Year = wn.Year,
                                                   Chapter = wn.Chapter,
                                                   Url = wn.Url,
                                                   Image = wn.Image
                                               }).FirstOrDefault();
                return View(result);
            }
        }

        // GET: Detail manga
        public ActionResult mangaDetails(int? id)
        {
            if (id == 0)
                return HttpNotFound();
            if (!id.HasValue)
                return HttpNotFound();
            else
            {
                string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"\Data\Data.json");
                var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
                DataModel.Manga result = root.listMangas.Where(manga => manga.ID == id)
                                               .Select(manga => new DataModel.Manga
                                               {
                                                   ID = manga.ID,
                                                   Name = manga.Name,
                                                   Associated_Name = manga.Associated_Name,
                                                   Description = manga.Description,
                                                   Genre = manga.Genre,
                                                   Authors = manga.Authors,
                                                   Artits = manga.Artits,
                                                   Year = manga.Year,
                                                   Chapter = manga.Chapter,
                                                   Url = manga.Url,
                                                   Image = manga.Image
                                               }).FirstOrDefault();
                return View(result);
            }
        }
    }
}

Test/Controllers/ListController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models;

namespace Test.Controllers
{
    public class ListController : Controller
    {
        // GET: Book
        public ActionResult LightNovels()
        {
            string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory+ @"\Data\Data.json");
            var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
            return View(root);
        }
        public ActionResult WebNovels()
        {
            string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"\Data\Data.json");
            var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
            return View(root);
        }
        public ActionResult Mangas()
        {
            string json = System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"\Data\Data.json");
            var root = JsonConvert.DeserializeObject<DataModel.Rootobject>(json);
            return View(root);
        }
    }
}

Test/Views/List/LightNovels.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "LightNovels";
    @model Test.Models.DataModel.Rootobject
}
<div class="container table-responsive-sm">
    <table class="table table-hover table-condensed">
        <caption>Liste des LightNovels</caption>
        <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col" colspan="3">Nom</th>
                <th scope="col" colspan="5">Description</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var ln in Model.listLightNovels)
                {
                    <tr>
                        <th scope="row">@ln.ID</th>
                        <td colspan="3">@ln.Name</td>
                        <td colspan="5">@ln.Description</td>
                        <td><a class="btn btn-info" href="@Url.Action("lnDetails", "Detail", new { id = ln.ID })" role="button">+Info</a></td>
                    </tr>

                }
            }
        </tbody>
    </table>


</div>

Test/Views/List/Mangas.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Mangas";
    @model Test.Models.DataModel.Rootobject
}
<div class="container table-responsive-sm">
    <table class="table table-hover table-condensed">
        <caption>Liste des Mangas</caption>
        <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col" colspan="3">Nom</th>
                <th scope="col" colspan="5">Description</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var manga in Model.listMangas)
                {
                        <tr>
                            <th scope="row">@manga.ID</th>
                            <td colspan="3">@manga.Name</td>
                            <td colspan="5">@manga.Description</td>
                            <td><a class="btn btn-info" href="@Url.Action("mangaDetails", "Detail", new { id = manga.ID })" role="button">+Info</a></td>
                        </tr>

                }
            }
        </tbody>
    </table>


</div>

Test/Views/List/WebNovels.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "WebNovels";
    @model Test.Models.DataModel.Rootobject
}
<div class="container table-responsive-sm">
    <table class="table table-hover table-condensed">
        <caption>Liste des WebNovels</caption>
        <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col" colspan="3">Nom</th>
                <th scope="col" colspan="5">Description</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var wn in Model.listWebNovels)
                {
                    <tr>
                        <th scope="row">@wn.ID</th>
                        <td colspan="3">@wn.Name</td>
                        <td colspan="5">@wn.Description</td>
                        <td><a class="btn btn-info" href="@Url.Action("wnDetails", "Detail", new { id = wn.ID })" role="button">+Info</a></td>
                    </tr>

                }
            }
        </tbody>
    </table>


</div>